import os
from glob import glob

from setuptools import find_packages, setup

package_name = 'hospital_reception'

setup(
    name=package_name,
    version='1.0.0',
    # find_packages picks up both the main `hospital_reception` module package
    # and the top-level `scripts` package (which holds the demo driver).
    packages=find_packages(exclude=['test']),
    data_files=[
        # ament resource index marker
        ('share/ament_index/resource_index/packages',
            ['resource/' + package_name]),
        # package manifest
        ('share/' + package_name, ['package.xml']),
        # launch files
        (os.path.join('share', package_name, 'launch'), glob('launch/*.py')),
        # semantic-memory JSON knowledge base
        (os.path.join('share', package_name, 'data'), glob('data/*.json')),
        # Nav2 / SLAM configs
        (os.path.join('share', package_name, 'config'), glob('config/*.yaml')),
        # Gazebo world
        (os.path.join('share', package_name, 'worlds'), glob('worlds/*.world')),
        # maps (placeholder + generated by SLAM)
        (os.path.join('share', package_name, 'maps'),
            glob('maps/*.yaml') + glob('maps/*.pgm')),
    ],
    install_requires=['setuptools'],
    zip_safe=True,
    maintainer='HRAI Student',
    maintainer_email='khanfaraz39767@gmail.com',
    description='HRAI TIAGo hospital reception / guide robot (CPU-only).',
    license='MIT',
    tests_require=['pytest'],
    entry_points={
        'console_scripts': [
            # node_name = package.module:main
            'interaction_node = hospital_reception.interaction_node:main',
            'reasoning_node = hospital_reception.reasoning_node:main',
            'navigation_node = hospital_reception.navigation_node:main',
            # convenience demo driver (top-level `scripts` package)
            'run_demo = scripts.run_demo:main',
        ],
    },
)
